natalina/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from web.views import *
from web import views
from web.views import welcome

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", all_productos_view, name="index"),  
    path("about/", about, name="about"),
    path("contacto/", contacto, name="contacto"),
    path("tyc/", tyc, name="terminos"),
    #usuario
    path('registration/', include('django.contrib.auth.urls')),
    path('perfil/', actualizar_usuario, name='actualizar_usuario'),
    path('registro/', registro_usuario, name='registro_usuario'),
    path("welcome/",welcome,name="welcome"),
    path("exito/", exito, name="exito"),
    #productos
    path('producto/<int:producto_id>/', prod_detail, name='prod_detail'),
    path('search/', search_view, name='buscar'),
    # detalle cada producto
    path('pasta/<int:producto_id>/', pasta_detail_view, name='pasta_detail'),
    path('salsa/<int:producto_id>/', salsa_detail_view, name='salsa_detail'),
    path('dulce/<int:producto_id>/', dulce_detail_view, name='dulce_detail'),
    path('coctel/<int:producto_id>/', coctel_detail_view, name='coctel_detail'),
    # listar productos
    path('pasta/', list_all_pasta_view, name='list_all_pasta'),
    path('salsa/', list_all_salsa_view, name='list_all_salsa'),
    path('dulce/', list_all_dulce_view, name='list_all_dulce'),
    path('coctel/', list_all_coctel_view, name='list_all_coctel'),
    path('politica/', politica, name='politica'),
    # Carrito de compra
    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/', views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/', views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/',views.cart_detail,name='cart_detail'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

onlyflans/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from web.views import *
from web import views
from web.views import welcome

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", all_productos_view, name="index"),  
    path("about/", about, name="about"),
    path("contacto/", contacto, name="contacto"),
    path("tyc/", tyc, name="terminos"),
    #usuario
    path('registration/', include('django.contrib.auth.urls')),
    path('perfil/', actualizar_usuario, name='actualizar_usuario'),
    path('registro/', registro_usuario, name='registro_usuario'),
    path("welcome/",welcome,name="welcome"),
    path("exito/", exito, name="exito"),
    #productos
    path('producto/<int:producto_id>/', prod_detail, name='prod_detail'),
    path('search/', search_view, name='buscar'),
    # detalle cada producto
    path('pasta/<int:producto_id>/', pasta_detail_view, name='pasta_detail'),
    path('salsa/<int:producto_id>/', salsa_detail_view, name='salsa_detail'),
    path('dulce/<int:producto_id>/', dulce_detail_view, name='dulce_detail'),
    path('coctel/<int:producto_id>/', coctel_detail_view, name='coctel_detail'),
    # listar productos
    path('pasta/', list_all_pasta_view, name='list_all_pasta'),
    path('salsa/', list_all_salsa_view, name='list_all_salsa'),
    path('dulce/', list_all_dulce_view, name='list_all_dulce'),
    path('coctel/', list_all_coctel_view, name='list_all_coctel'),
    path('politica/', politica, name='politica'),
    # Carrito de compra
    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/', views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/', views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/',views.cart_detail,name='cart_detail'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/models.py
from django.db import models
import uuid
from django.utils.text import slugify
from django.contrib.auth.models import User

# Create your models here.

class Producto(models.Model):
    producto_uuid = models.UUIDField(default= uuid.uuid4, editable= False, unique=True)
    name = models.CharField(max_length=64)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=0)
    image = models.ImageField(upload_to='',null=True, blank=True)
    slug = models.SlugField(unique=True, blank=True)
    is_private = models.BooleanField(default=False)

    def save(self,*args,**kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args,**kwargs)

    def __str__(self):
        return self.name

class Pasta(Producto):
    tipo_pasta = models.CharField(max_length=100)

class Salsa(Producto):
    tipo_salsa = models.CharField(max_length=100)

class Dulce(Producto):
    tipo_dulce = models.CharField(max_length=100)

class Coctel(Producto):
    tipo_coctel = models.CharField(max_length=100)

class ContactForm(models.Model):
    contact_form_uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    customer_email = models.EmailField()
    customer_name = models.CharField(max_length=64)
    message = models.TextField()

    def __str__(self):
        return self.customer_name
    
class Usuario(User):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    rut = models.CharField(max_length=10, unique=True)
    direccion = models.CharField(max_length=100)
    telefono = models.CharField(max_length=15)
    correo_electronico = models.EmailField(unique=True, default='correo@correo.cl') 

    def __str__(self):
        return f"{self.nombre} {self.apellido}"

web/templates/about.html
{% extends 'base.html' %}
{%load static%}


{% block content %}
<div class="container my-5">
    <h1 class="text-center mb-5">Quienes somos</h1>
    <div class="row align-items-center">
        <div class="col-md-4 mb-4 mb-md-0 d-none d-md-block">
            <img src="{% static 'about.jpg' %}" class="img-fluid" alt="Vertical Image">
        </div>
        <div class="col-md-8">
            <h3 class="mb-4">10 años en el mercado elaborando pastas frescas y salsas con las mejores materias primas. El resultado: Productos de Calidad Gourmet. 
                Vendemos por mayor para que puedas ofrecer a tus clientes una experiencia italiana inigualable.</h3>
            <div class="row mb-4 d-none d-md-flex">
                <div class="col-4">
                    <img src="{% static 'about_1.jpg' %}" class="img-fluid" alt="Image 1" style="height: 250px; object-fit: cover;">
                </div>
                <div class="col-4">
                    <img src="{% static 'about_2.jpg' %}" class="img-fluid" alt="Image 2" style="height: 250px; object-fit: cover;">
                </div>
                <div class="col-4">
                    <img src="{% static 'about_3.jpg' %}" class="img-fluid" alt="Image 3" style="height: 250px; object-fit: cover;">
                </div>
            </div>
            <ul class="list-unstyled mb-4">
                <li class="mb-2">Pastas y Salsas para Veganos.</li>
                <li class="mb-2">Tartas y Dulces.</li>
                <li class="mb-2">Productos para Banquetería.</li>
                <li class="mb-2">Y traemos directamente de Italia el mejor café de grano: Maskafé.</li>
            </ul>
            <h4>Somos una muy buena alternativa para externalizar procesos, ahorrar mano de obra y ampliar tu oferta de productos.</h4>
        </div>
    </div>
</div>
{% endblock %}

web/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!--IE11-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/7.12.1/polyfill.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/classlist/1.2.20171210/classList.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/element-closest/2.0.2/element-closest.min.js"></script>
    <!--bootstrap-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.rtl.min.css"
    integrity="sha384-dpuaG1suU0eT09tx5plTaGMLBsfDLzUCCUXOY2j/LSvXYuG6Bqs43ALlhIqAJVRb" crossorigin="anonymous">
    <!--fontawesome-->
    <script src="https://kit.fontawesome.com/d619ad2787.js" crossorigin="anonymous"></script>
    <!--node-->
    <script src="https://cdn.jsdelivr.net/npm/node"></script>
    <!--css-->
    <link rel="stylesheet" type="text/css" href="{% static 'web/css/style.css' %}">
    {% block extra_css %}{% endblock %}
    <!--favicon-->
    <link rel="icon" href="{% static 'favicon.jpg'%}" type="image/x-icon">
    <title>{% block 'title' %}Los Sabores De Natalina{% endblock %}</title>
</head>
<body>
    <div class="d-flex flex-column min-vh-100">
        <!--BLOQUE NAVBAR-->
        {% block 'navbar' %}
        {% include 'includes/navbar.html'%}
        {% endblock %}

        <!--BLOQUE HEADER-->
        {% block header %}
        {% include 'includes/header.html'%}
        {% endblock %}

        <!--BLOQUE CONTENT-->
        {% block content %}
        <div class="flex-grow-1">
        </div>
        {% endblock %}

        <!--BLOQUE FOOTER-->
        {% block footer %}
        {% include 'includes/footer.html'%}
        {% endblock %}

        <!--BLOQUE JS-->
        {% block javascript %}
        {% include 'includes/scripts.html' %}
        {% endblock %}
    </div>
</body>
</html>

web/templates/busqueda.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- busqueda.html -->
<div class="container">
    <h2>Resultados</h2>
    <div class="row">
      {% if results %}
        {% for result in results %}
        <div class="col-md-4">
          <div class="card mb-3">
            <div class="card-body">
              <img src="{{ result.image.url }}" alt="{{ result.name }}" class="card-img-top" style="height: 200px; object-fit: cover;">
              <p class="card-text">{{ result.description }}</p>
              <!-- detalles u otras cosas necesarias -->
              <a href="{% url 'prod_detail' result.id %}" class="btn btn-primary">Detalle</a>
            </div>
          </div>
        </div>
        {% endfor %}
      {% else %}
        <p>No existen productos bajo este nombre</p>
      {% endif %}
    </div>
  </div>
  

{% endblock %}

web/templates/contacto.html
{% extends 'base.html' %}
{%load static%}


{% block header %}
<div class="header-style" style="background: none; text-align: center;">
    <img src="{% static 'logo.png' %}" style="height: 200px;" alt="Logo">
</div>
{% endblock %}

{% block content %}
<div class="container" justify="left" align="center" >
    <h1>Contáctanos</h1>
    <form method="POST" class="row col-md-4 col-lg-8" >
        {% csrf_token %}
        {{form.non_field_errors}}
        {{form.customer_email.label_tag}}   
        {{form.customer_email}}
        {{form.customer_email.errors}}
        <p class="text-warning bg-dark">{{form.customer_email.errors}}</p>
        {{form.customer_name.label_tag}}
        {{form.customer_name}}
        {{form.customer_name.errors}}
        <p class="text-warning bg-dark">{{form.customer_name.errors}}</p>
        {{form.message.label_tag}}
        {{form.message}}
        <p class="text-warning bg-dark">{{form.message.errors}}</p>
        <input type="submit">
    </form>
</div>
{% endblock %}

web/templates/dulce_detail.html
{% extends "base.html" %}
{% block content %}

<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-4">
            <img src="{{ dulce.image_url.url }}" class="img-fluid rounded mx-auto d-block" style="max-width: 100%;">
        </div>
        <div class="col-md-8">
            <div class="card border-0 h-100">
                <div class="card-body d-flex flex-column justify-content-between">
                    <div>
                        <h5 class="card-title">{{ dulce.name }}</h5>
                        <p class="card-text">{{ dulce.description }}</p>
                        <p class="card-text">Precio: ${{ dulce.price }}</p>
                    </div>
                    <div>
                        <a href="{% url 'index' %}" class="btn btn-primary align-self-end">Volver al inicio</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% if random_prod %}
<div class="row mt-4 mb-4">
    {% for random_product in random_prod %}
    <div class="col-md-4 mb-4">
        <div class="card border-0 h-100">
            <img src="{{ random_product.image_url.url }}" class="card-img-top" style="height: 200px; object-fit: cover;">
            <div class="card-body text-center">
                <h5 class="card-title"><a href="{% url 'prod_detail' random_product.id %}">{{ random_product.name }}</a></h5>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endif %}
</div>
{% endblock %}

web/templates/exito.html
{% extends 'base.html' %}

{% block content %}
<div style="text-align: center;">
    <h1>Gracias por contactarte con Los sabores de Natalina,</h1>
    <h1>te responderemos en breve</h1>
    <a href="{% url 'index' %}" class="btn btn-primary">Volver al inicio</a>
</div>
{% endblock %}

web/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!--Carousel-->

<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel" data-interval="1500">
    <div class="carousel-item active">
      <img src="{% static '/carrousel_items/carrousel_1.jpg'%}" class="d-block w-100" alt="Slide 1">
    </div>
    <div class="carousel-item">
      <img src="{% static '/carrousel_items/carrousel_2.jpg'%}" class="d-block w-100" alt="Slide 2">
    </div>
    <div class="carousel-item">
      <img src="{% static '/carrousel_items/carrousel_3.jpg'%}" class="d-block w-100" alt="Slide 3">
    </div>
    <div class="carousel-item">
      <img src="{% static '/carrousel_items/carrousel_4.jpg'%}" class="d-block w-100" alt="Slide 4">
    </div>
    <div class="carousel-item">
      <img src="{% static '/carrousel_items/carrousel_5.jpg'%}" class="d-block w-100" alt="Slide 5">
    </div>
    <div class="carousel-item">
      <img src="{% static '/carrousel_items/carrousel_6.jpg'%}" class="d-block w-100" alt="Slide 6">
    </div>
    <div class="carousel-item">
      <img src="{% static '/carrousel_items/carrousel_7.jpg'%}" class="d-block w-100" alt="Slide 7">
    </div>
  </div>
  
<!--Cards-->

<div class="container-fluid bg-dark text-light" style="padding-top: 20px;">
  <div class="row justify-content-center">
    <div class="col-9">
      <div class="row">
        {% if productos %}
        {% for prod in productos %}
            <div class="col-md-4 col-lg-3">
                <div class="card mb-3">
                    {% if prod.image %}
                        <img src="{{ prod.image.url }}" class="card-img-top" style="height: 200px; object-fit: cover;">
                    {% else %}
                        <img src="{% static 'default_image.jpg' %}" class="card-img-top" style="height: 200px; object-fit: cover;">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{ prod.name }}</h5>
                        <a href="{% url 'prod_detail' prod.id %}" class="btn btn-primary">Detalle</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p>No products available</p>
    {% endif %}
      </div>
    </div>
  </div>
</div>




{% endblock %}

web/templates/pasta_detail.html
{% extends "base.html" %}
{% block content %}

<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-4">
            <img src="{{ pasta.image_url.url }}" class="img-fluid rounded mx-auto d-block" style="max-width: 100%;">
        </div>
        <div class="col-md-8">
            <div class="card border-0 h-100">
                <div class="card-body d-flex flex-column justify-content-between">
                    <div>
                        <h5 class="card-title">{{ pasta.name }}</h5>
                        <p class="card-text">{{ pasta.description }}</p>
                        <p class="card-text">Precio: ${{ pasta.price }}</p>
                    </div>
                    <div>
                        <a href="{% url 'index' %}" class="btn btn-primary align-self-end">Volver al inicio</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% if random_prod %}
<div class="row mt-4 mb-4">
    {% for random_product in random_prod %}
    <div class="col-md-4 mb-4">
        <div class="card border-0 h-100">
            <img src="{{ random_product.image_url.url }}" class="card-img-top" style="height: 200px; object-fit: cover;">
            <div class="card-body text-center">
                <h5 class="card-title"><a href="{% url 'prod_detail' random_product.id %}">{{ random_product.name }}</a></h5>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endif %}
</div>


{% endblock %}

web/templates/perfil.html
{% extends 'base.html' %}
{% block content %}
<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f7f7f7;
        margin: 0;
        padding: 0;
    }
    #form-container {
        width: 80%;
        max-width: 600px;
        margin: 50px auto;
        background-color: #fff;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }
    #form-container h2 {
        text-align: center;
        color: #333;
        margin-top: 20px;
    }
    #form-container form {
        margin-top: 20px;
    }
    #form-container button {
        background-color: #007bff;
        color: #fff;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
        margin-top: 20px;
    }
    #form-container button:hover {
        background-color: #0056b3;
    }
    #form-container input[type="text"],
    #form-container input[type="correo_electronico"] {
        width: 100%;
        padding: 10px;
        margin-top: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-sizing: border-box;
    }
    #form-container label {
        color: #333;
        margin-top: 10px;
        display: block;
    }
</style>


<div id="form-container">
    <h2 class="text-center pt-5">Actualizar Datos</h2>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="nombre">Nombre:</label>
            <input type="text" id="nombre" name="nombre" required>
        </div>
        <div class="form-group">
            <label for="apellido">Apellido:</label>
            <input type="text" id="apellido" name="apellido" required>
        </div>
        <div class="form-group">
            <label for="correo_electronico">Correo Electrónico:</label>
            <input type="correo_electronico" id="correo_electronico" name="correo_electronico" required>
        </div>
        <button type="submit">Actualizar</button>
    </form>
</div>

{% endblock %}

web/templates/politica.html
{% extends "base.html" %}
{% block content %}

<div class="policy container mt-4">
    <h2>Política de Devolución de Producto y Dinero</h2>
    <p>En Los sabores de Natalina, nos esforzamos por garantizar la satisfacción total de nuestros clientes. 
        Si por alguna razón no estás completamente satisfecho con tu compra, ofrecemos una política de devolución que te permite devolver el producto y 
        recibir un reembolso completo o un cambio por otro artículo.</p>

    <h3>Condiciones de Devolución:</h3>
    <ul>
        <li>Los productos deben devolverse en su estado original, sin abrir y con el empaque intacto.</li>
        <li>Se requiere presentar el recibo de compra o comprobante de pago.</li>
        <li>El período de devolución es de [número de días], a partir de la fecha de compra.</li>
    </ul>

    <h3>Proceso de Devolución:</h3>
    <ol>
        <li>Comunícate con nuestro equipo de atención al cliente para notificar tu intención de devolver el producto.</li>
        <li>Embalaje cuidadosamente el producto y asegúrate de incluir todos los accesorios y documentos originales.</li>
        <li>Envía el producto de vuelta a nuestra dirección de devolución, utilizando un servicio de envío con seguimiento.</li>
        <li>Una vez recibido el producto, nuestro equipo de control de calidad verificará su estado.</li>
        <li>Si se cumplen todas las condiciones de devolución, procederemos a procesar tu reembolso o cambio según lo solicitado.</li>
    </ol>

    <p>Es importante tener en cuenta que los gastos de envío asociados con la devolución del producto correrán a cargo del cliente, 
        a menos que la devolución sea debido a un error nuestro o a un producto defectuoso.</p>

    <p>Para más información sobre nuestra política de devolución, no dudes en ponerte en contacto con nuestro equipo de atención al cliente.</p>
</div>
{% endblock %}

web/templates/registro_usuario.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'web/css/register.css' %}">
{% endblock %}
{% block content %}
<section class="bg-image"
    style="background-image: url('https://mdbcdn.b-cdn.net/img/Photos/new-templates/search-box/img4.webp');">
    <div class="mask d-flex align-items-center h-100 gradient-custom-3">
        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-9 col-lg-7 col-xl-6" style="padding-top: 20px;">
                    <div class="card" style="border-radius: 15px;">
                        <div class="card-body p-5">
                            <h2 class="text-uppercase text-center mb-5">Registrarse</h2>
                            <form method="post">
                                {% csrf_token %}
                                
                                <div data-mdb-input-init class="form-outline mb-4">
                                    <input type="text" id="nombre" name="nombre" class="form-control form-control-lg" required />
                                    <label class="form-label" for="nombre">Nombre</label>
                                    {% if form.nombre.errors %}
                                        <div class="text-danger">
                                            {{ form.nombre.errors|join:", " }}
                                        </div>
                                    {% endif %}
                                </div>
                                
                                <div data-mdb-input-init class="form-outline mb-4">
                                    <input type="text" id="apellido" name="apellido" class="form-control form-control-lg" required />
                                    <label class="form-label" for="apellido">Apellido</label>
                                    {% if form.apellido.errors %}
                                        <div class="text-danger">
                                            {{ form.apellido.errors|join:", " }}
                                        </div>
                                    {% endif %}
                                </div>
                                
                                <div data-mdb-input-init class="form-outline mb-4">
                                    <input type="text" id="rut" name="rut" class="form-control form-control-lg" required />
                                    <label class="form-label" for="rut">RUT</label>
                                    {% if form.rut.errors %}
                                        <div class="text-danger">
                                            {{ form.rut.errors|join:", " }}
                                        </div>
                                    {% endif %}
                                </div>
                                
                                <div data-mdb-input-init class="form-outline mb-4">
                                    <input type="text" id="direccion" name="direccion" class="form-control form-control-lg" required />
                                    <label class="form-label" for="direccion">Dirección</label>
                                    {% if form.direccion.errors %}
                                        <div class="text-danger">
                                            {{ form.direccion.errors|join:", " }}
                                        </div>
                                    {% endif %}
                                </div>
                                
                                <div data-mdb-input-init class="form-outline mb-4">
                                    <input type="text" id="telefono" name="telefono" class="form-control form-control-lg" required />
                                    <label class="form-label" for="telefono">Teléfono</label>
                                    {% if form.telefono.errors %}
                                        <div class="text-danger">
                                            {{ form.telefono.errors|join:", " }}
                                        </div>
                                    {% endif %}
                                </div>
                                
                                <div data-mdb-input-init class="form-outline mb-4">
                                    <input type="email" id="correo_electronico" name="correo_electronico" class="form-control form-control-lg" required />
                                    <label class="form-label" for="correo_electronico">Correo Electrónico</label>
                                    {% if form.correo_electronico.errors %}
                                        <div class="text-danger">
                                            {{ form.correo_electronico.errors|join:", " }}
                                        </div>
                                    {% endif %}
                                </div>
                                
                                <div data-mdb-input-init class="form-outline mb-4">
                                    <input type="password" id="password" name="password" class="form-control form-control-lg" required />
                                    <label class="form-label" for="password">Clave</label>
                                    {% if form.password.errors %}
                                        <div class="text-danger">
                                            {{ form.password.errors|join:", " }}
                                        </div>
                                    {% endif %}
                                </div>
                                
                                <div class="d-flex justify-content-center">
                                    <button type="submit" class="btn btn-success btn-block btn-lg gradient-custom-4 text-body">Registrarse</button>
                                </div>
                                <p class="text-center text-muted mt-5 mb-0">¿Ya tienes una cuenta? <a href="{% url 'login' %}" class="fw-bold text-body"><u>Inicia sesión aquí</u></a></p>
                            </form>
                            {% if form.errors %}
                            <div class="alert alert-danger mt-3">
                                <strong>Error:</strong> Por favor, corrige los errores en el formulario.
   <form method="post">
       {% csrf_token %}
       
       <div data-mdb-input-init class="form-outline mb-4">
           {{ form.nombre }}
           <label class="form-label" for="id_nombre">Nombre</label>
           {% if form.nombre.errors %}
               <div class="text-danger">
                   {{ form.nombre.errors|join:", " }}
               </div>
           {% endif %}
       </div>
       
       <div data-mdb-input-init class="form-outline mb-4">
           {{ form.apellido }}
           <label class="form-label" for="id_apellido">Apellido</label>
           {% if form.apellido.errors %}
               <div class="text-danger">
                   {{ form.apellido.errors|join:", " }}
               </div>
           {% endif %}
       </div>
       
       <div data-mdb-input-init class="form-outline mb-4">
           {{ form.rut }}
           <label class="form-label" for="id_rut">RUT</label>
           {% if form.rut.errors %}
               <div class="text-danger">
                   {{ form.rut.errors|join:", " }}
               </div>
           {% endif %}
       </div>
       
       <div data-mdb-input-init class="form-outline mb-4">
           {{ form.direccion }}
           <label class="form-label" for="id_direccion">Dirección</label>
           {% if form.direccion.errors %}
               <div class="text-danger">
                   {{ form.direccion.errors|join:", " }}
               </div>
           {% endif %}
       </div>
       
       <div data-mdb-input-init class="form-outline mb-4">
           {{ form.telefono }}
           <label class="form-label" for="id_telefono">Teléfono</label>
           {% if form.telefono.errors %}
               <div class="text-danger">
                   {{ form.telefono.errors|join:", " }}
               </div>
           {% endif %}
       </div>
       
       <div data-mdb-input-init class="form-outline mb-4">
           {{ form.correo_electronico }}
           <label class="form-label" for="id_correo_electronico">Correo Electrónico</label>
           {% if form.correo_electronico.errors %}
               <div class="text-danger">
                   {{ form.correo_electronico.errors|join:", " }}
               </div>
           {% endif %}
       </div>
       
       <div data-mdb-input-init class="form-outline mb-4">
           {{ form.password }}
           <label class="form-label" for="id_password">Clave</label>
           {% if form.password.errors %}
               <div class="text-danger">
                   {{ form.password.errors|join:", " }}
               </div>
           {% endif %}
       </div>
       
       <div class="d-flex justify-content-center">
           <button type="submit" class="btn btn-success btn-block btn-lg gradient-custom-4 text-body">Registrarse</button>
       </div>
       <p class="text-center text-muted mt-5 mb-0">¿Ya tienes una cuenta? <a href="{% url 'login' %}" class="fw-bold text-body"><u>Inicia sesión aquí</u></a></p>
   </form>
  
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}
  

web/templates/welcome.html
{% extends 'base.html' %}
{% block content %}

<div class="card-body bienvenido bg-dark" style="padding-top: 20px;" >
    <h1 class="card-title text-center">Welcome {{ user.username }}</h1>
</div>


{% endblock %}